---
title: "PB18000029舒文炫r语言作业"
author: "舒文炫"
date: "2021/5/17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 画岭迹图
```{r }
import=read.table("1.txt",header = TRUE)
##标准化x
x<-import[,1:4]
xm=colMeans(x)
xms=0
c=9*cov(x)
xc<-x-matrix(rep(1,10),nrow = 10)%*%t(xm)
xs<-matrix(rep(0,40),ncol=4)
for(i in 1:4)
  xs[,i]<-xc[,i]/sqrt(c[i,i])
##标准化y
y=import[,5]
yc=y-mean(y)
syy<-crossprod(yc)
s<-1/sqrt(syy)
ys<-yc%*%s



##制作表
p=4
m=20
beta=matrix(rep(0,p*m),ncol=m)
RSS=0
Tab=matrix(rep(0,(p+2)*m),nrow=m)

dimnames(Tab)=list(seq(1,by=1,length=20))
paste(c("k","bs1","bs2","bs3","bs4","RSS"))

R<-cor(x)
##前10次增量0.001，后10次增量0.01
for(k in 1:10){
  beta[,k]=solve(R+(k-1)/1000*diag(p))%*%t(xs)%*%ys
  RSS[k]=syy*sum((ys-xs%*%beta[,k])^2)
  Tab[k,]=c((k-1)/1000,beta[,k],RSS[k])
  
}
for(k in 11:20){
  beta[,k]=solve(R+(k-10)/100*diag(p))%*%t(xs)%*%ys
  RSS[k]=syy*sum((ys-xs%*%beta[,k])^2)
  Tab[k,]=c((k-10)/100,beta[,k],RSS[k])
  
}
##打印表
print(Tab)

##使用ggplot画图
library(ggplot2)
data=data.frame(Tab[,1:5])
colnames(data)<-NULL
dimnames(data)=list(seq(1,20,1),paste(c("k","bs1","bs2","bs3","bs4")))


ggplot(data,aes(x=k))+geom_smooth(aes(y=bs1),lty=2,col="red",se=FALSE)+
  geom_smooth(aes(y=bs2),lty=2,col="blue",se=FALSE)+
  geom_smooth(aes(y=bs3),lty=4,col="yellow",se=FALSE)+
  geom_smooth(aes(y=bs4),lty=1,col="black",se=FALSE)
plot.new()
legend("topright",title="商品销量岭迹图",c("bs1","bs2","bs3","bs4"),lty=c(2,2,4,1),col=c("red","blue","yellow","black"))
##常数项

qwq=0
for(i in 1:4)
  qwq[i]<-beta[i,15]/sqrt(c[i,i])*sqrt(syy)
alpha=(mean(y)-t(qwq)%*%xm)
print("常数项为")
print(alpha)
print("偏回归系数为")
print(qwq)
```
从图中看出在k=0.05时趋于平缓，我们可以取k为0.05
对应四个偏回归系数0.003359705 0.003981948 0.005861257 0.015377487
常数项-20.12184
当然我们也有另一种方法来画岭迹图，直接调用ridge包
```{r}
library(ridge)
library(MASS)
import=read.table("1.txt",header = TRUE)
##标准化x
x<-import[,1:4]
xm=colMeans(x)
c=9*cov(x)
xc<-x-matrix(rep(1,10),nrow = 10)%*%t(xm)
xs<-matrix(rep(0,40),ncol=4)
for(i in 1:4)
  xs[,i]<-xc[,i]*1/sqrt(c[i,i])

##标准化y
y=import[,5]
yc=y-mean(y)
syy<-crossprod(yc)
s<-1/sqrt(syy)
ys<-yc%*%s


plot(linearRidge(ys~xs,lambda=seq(0,0.1,0.001)))
```


##主成分分析
```{r}
import=read.table("1.txt",header = TRUE)
##标准化x
x<-import[,1:4]
xm=colMeans(x)
c=9*cov(x)
xc<-x-matrix(rep(1,10),nrow = 10)%*%t(xm)
xs<-matrix(rep(0,40),ncol=4)
for(i in 1:4)
  xs[,i]<-xc[,i]*1/sqrt(c[i,i])
##标准化y
y=import[,5]
yc=y-mean(y)
syy<-crossprod(yc)
s<-1/sqrt(syy)
ys<-yc%*%s

s=t(xs)%*%xs
eig=eigen(s)
lambda<-eig$val
vect<-eig$vec
print(lambda)
print(vect)
##0.00364很小，我们剔除第四个主成分
lambda1=lambda[1:3]
vect1=vect[,1:3]
lambda1=diag(lambda1)
beta=vect1%*%solve(lambda1)%*%t(vect1)%*%t(xs)%*%ys
print("偏回归系数为")
beta2=0
for(i in 1:4)
  beta2[i]=beta[i]/sqrt(c[i,i])*sqrt(syy)
print(beta2) 
print("常数项为")
alpha=(mean(y)-t(beta2)%*%xm)
print(alpha)
```