---
title: "PB18000029"
author: "舒文炫"
date: "2021/5/18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##5.20(a)
```{r }
library(car)
library(plotrix)

x=read.table("1.DAT")
m=colMeans(x)
s=cov(x)
re=eigen(s)
lam=re$val
ve=re$vec
print(ve)
f1=2*44/43/45*qf(0.95,2,43)
plot(x)
draw.ellipse(m[1],m[2],sqrt(lam[2]*f1),sqrt(lam[1]*f1),angle=-atan(ve[1,1]/ve[2,1]),deg=FALSE)


mx=c(190,275)
me=m-mx
t1=t(me)%*%solve(s/45)%*%me
t1
f1*45
```
检验发现在，从而对雌性来说是plausible的
## (b)
```{r }
x=read.table("1.DAT")
m=colMeans(x)
s=cov(x)
p=2
n=45
##simultaneous confidence intervals
for(i in 1:2){
  f1=sqrt(p*(n-1)/(n-p)*qf(0.95,p,n-p))
  down=m[i]-f1*sqrt(s[i,i]/n)
  up=m[i]+f1*sqrt(s[i,i]/n)
  cat("the simultaneous  interval is [",down,",",up,"]\n")
}
for(i in 1:2){
  t1=qt(0.9875,n-1)
  down=m[i]-t1*sqrt(s[i,i]/n)
  up=m[i]+t1*sqrt(s[i,i]/n)
  cat("the bonferroni  interval is [",down,",",up,"]\n")
}
```
simultaneous interval is larger than bonferroni interval
## c
```{r}
x=read.table("1.DAT")
for(i in 1:2){
  b<-qqnorm(x[,i])
  x1<-b$x
  y1<-b$y
  print(cor(x1,y1))
  
}
plot(x)
```

## 5.22(a)
```{r }
x=read.table("T5-13.dat")
for(i in 1:3){
  b<-qqnorm(x[,i])
  x1<-b$x
  y1<-b$y
  print(cor(x1,y1))
}
plot(x[,1],x[,2])
plot(x[,2],x[,3])
plot(x[,3],x[,1])


```
移除x1=29.11,x1=26.16两个异常值点
```{r }
x=read.table("T5-13.dat")
x=x[-9,]
x=x[-20,]
for(i in 1:3){
  b<-qqnorm(x[,i])
  x1<-b$x
  y1<-b$y
  print(cor(x1,y1))
}
plot(x[,1],x[,2])
plot(x[,2],x[,3])
plot(x[,3],x[,1])

```
正态性变好了

## (b)
```{r }
x=read.table("T5-13.dat")
m=colMeans(x)
s=cov(x)
p=3
n=25
##全部的数据
##simultaneous confidence intervals
for(i in 1:3){
  f1=sqrt(p*(n-1)/(n-p)*qf(0.95,p,n-p))
  down=m[i]-f1*sqrt(s[i,i]/n)
  up=m[i]+f1*sqrt(s[i,i]/n)
  cat("the simultaneous  interval is [",down,",",up,"]\n")
}
for(i in 1:3){
  t1=qt(0.9875,n-1)
  down=m[i]-t1*sqrt(s[i,i]/n)
  up=m[i]+t1*sqrt(s[i,i]/n)
  cat("the bonferroni  interval is [",down,",",up,"]\n")
}
```

## 去除异常值点
```{r }
x=read.table("T5-13.dat")
x=x[-c(9,21),]
m=colMeans(x)
s=cov(x)
p=3
n=23
##全部的数据
##simultaneous confidence intervals
for(i in 1:3){
  f1=sqrt(p*(n-1)/(n-p)*qf(0.95,p,n-p))
  down=m[i]-f1*sqrt(s[i,i]/n)
  up=m[i]+f1*sqrt(s[i,i]/n)
  cat("the simultaneous  interval is [",down,",",up,"]\n")
}
for(i in 1:3){
  t1=qt(1-0.05/2/3,n-1)
  down=m[i]-t1*sqrt(s[i,i]/n)
  up=m[i]+t1*sqrt(s[i,i]/n)
  cat("the bonferroni  interval is [",down,",",up,"]\n")
}
```

##5.23(a)
```{r }
x=read.table("T6-13.DAT")
x=x[c(1:30),c(1:4)]
##qqnorm
for(i in 1:4){
  b<-qqnorm(x[,i])
  x1<-b$x
  y1<-b$y
  print(cor(x1,y1))
}
##chisqplot
m=colMeans(x)
xm=x-c(rep(1,times=length(x[,1])))%*%t(c(rep(1,times=4)))%*%diag(m)
s=cov(x)
xm=t(xm)
d=t(xm)%*%solve(s)%*%xm
d=diag(d)
d=d[order(d)]
q<-qchisq(seq(1/60,59/60,1/30),4)
plot(q,d)
r1=cor(q,d)
r1
```
## (b)
```{r }
x=read.table("T6-13.DAT")
x=x[c(1:30),c(1:4)]
m=colMeans(x)
s=cov(x)
p=4
n=30
##simultaneous confidence intervals
for(i in 1:4){
  f1=sqrt(p*(n-1)/(n-p)*qf(0.95,p,n-p))
  down=m[i]-f1*sqrt(s[i,i]/n)
  up=m[i]+f1*sqrt(s[i,i]/n)
  cat("the simultaneous  interval is [",down,",",up,"]\n")
}
for(i in 1:4){
  t1=qt(1-0.05/2/p,n-1)
  down=m[i]-t1*sqrt(s[i,i]/n)
  up=m[i]+t1*sqrt(s[i,i]/n)
  cat("the bonferroni  interval is [",down,",",up,"]\n")
}
```

## 6.16
```{r }
x=read.table("T4-3.DAT")
x=x[,c(1:4)]
C=matrix(c(1,1,1,-1,0,0,0,-1,0,0,0,-1),ncol=4,nrow=3)
m=colMeans(x)
s=cov(x)
n=30
q=4
f1=(n-1)*(q-1)/(n-q+1)*qf(0.95,q-1,n-q+1)
c1=c(1,1,-1,-1)
up=c1%*%m+sqrt(f1)*sqrt(t(c1)%*%s%*%c1/n)
down=c1%*%m-sqrt(f1)*sqrt(t(c1)%*%s%*%c1/n)
cat("the simultaneous  interval is [",down,",",up,"]\n")
```