---
title: "第四次上机"
author: "舒文炫"
date: "2021/5/10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 5.18(a)
```{r }
x=read.table("T5-2.DAT")
m=colMeans(x)
s=cov(x)
f1=3*86/84*qf(0.95,3,84)
for(i in c(1:3)){
  inf1=m[i]-sqrt(f1)*sqrt(s[i,i]/length(x[,1]))
  sup1=m[i]+sqrt(f1)*sqrt(s[i,i]/length(x[,1]))
  cat("the interval is [",inf1,",",sup1,"]\n")
  }

```
compute the T^2
```{r }
x=read.table("T5-2.DAT")
m=colMeans(x)
s=cov(x)
mx=c(500,50,30)
me=m-mx
t1=t(me)%*%solve(s/87)%*%me
t1
f1=3*86/84*qf(0.95,3,84)
f1
```
T^2 is bigger than f, we reject the hypothesis
it is different from students 10 years ago.

## (b)
```{r }
x=read.table("T5-2.DAT")
m=colMeans(x)
s=cov(x)
f1=3*86/84/87*qf(0.95,3,84)
ev<- eigen(s)
a=ev$val
b=ev$vec
for(i in c(1:3)){
  length1=2*sqrt(a[i])*sqrt(f1)
  cat("the length of axes is ", length1,"\n")
  print(b[,i])
}
```

## (c)
```{r }
x=read.table("T5-2.DAT")
m=colMeans(x)
s=cov(x)
for(i in c(1:3)){
  b=qqnorm(x[,i])
  x1<-b$x
  y1<-b$y
  r=cor(x1,y1)
  print(r)
}
plot(x[,1],x[,2])
plot(x[,2],x[,3])
plot(x[,3],x[,1])
```
It looks normal

## 5.19
```{r }
library(car)
library(plotrix)
x=read.table("T5-11.DAT")
m=colMeans(x)
s=cov(x)
re=eigen(s)
lam=re$val
ve=re$vec
print(ve)
f1=2*29/28/30*qf(0.95,2,28)
plot(x)
draw.ellipse(m[1],m[2],sqrt(lam[2]*f1),sqrt(lam[1]*f1),angle=-atan(ve[1,1]/ve[2,1]),deg=FALSE)
```
## (b)
```{r }
x=read.table("T5-11.DAT")
m=colMeans(x)
s=cov(x)
mx=c(2000,10000)
me=m-mx
t1=t(me)%*%solve(s/30)%*%me
t1
f1=2*29/28*qf(0.95,2,28)
f1
```
检验发现不在
## (c)
```{r }
x=read.table("T5-11.DAT")
m=colMeans(x)
s=cov(x)
mx=c(rep(1,times=length(x[,1])))%*%t((rep(1,times=length(x[1,]))))%*%diag(m)
xm=x-mx
xm=t(xm)
d=t(xm)%*%solve(s)%*%xm
d=diag(d)
d=d[order(d)]
q=qchisq(c(seq(1/60,59/60,1/30)),2)
plot(d,q)
r=cor(d,q)
r
```

```{r }
x=read.table("T5-11.DAT")
m=colMeans(x)
s=cov(x)
for(i in c(1:2)){
  b=qqnorm(x[,i])
  x1<-b$x
  y1<-b$y
  r=cor(x1,y1)
  print(r)
}
plot(x[,1],x[,2])
```
从qq图可以看出正态性很好，从散点图看出独立性很好